[target.'cfg(target_arch = "riscv32")']
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "force-frame-pointers",
]

[build]
target = "riscv32imc-unknown-none-elf"

[source.crates-io]
replace-with = "rsproxy"

[source.rsproxy]
registry = "sparse+https://rsproxy.cn/index/"

[env]
DEFMT_LOG = "info,esp_radio=warn,trouble_host=warn"

[unstable]
build-std = ["core"]
